repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
    - id: black
      language_version: python3.8
- repo: local
  hooks:
    - id: commit-message-check
      name: check commit message format
      entry: python3.8 scripts/commit_message.py
      language: python
      stages: [commit-msg]